image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build_job:
  stage: build
  script:
    - cd client
    - npm install
    - npm run build
  artifacts:
    paths:
      - client/dist/
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event"'

pages:
  stage: deploy
  script:
    - cd client
    - mv dist public_temp # Перемещаем dist во временную папку
    - rm -rf public # Удаляем старую public, если она есть
    - mv public_temp public # Переименовываем временную папку в public
    - mkdir -p ../public # Создаем папку public в корне, если её нет
    - cp -r public/* ../public/ # Копируем содержимое в корневую public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'